POST http://localhost:3000/api/signup/voter
Content-Type: application/json

{
  "email": "ajuwonore@gmail.com",
  "name": "Dornom Lovette Peter",
  "matric_no": "BU25MED1038",
  "level": 500,
  "payer_name": "Peter Dornom Lovette",
  "phone": "08166124505"
}